name: cicd workflow to create docker image and upload image into DockerHub
on:
  push:
    branches: ["main"]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        distriution: 'adopt'
        java-version: '17'
    - name: Build with Maven
      run: mvn clean install
    - name: Login to DockerHUB
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mydimages:${IMAGE_TAG} .
    - name: Push docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mydimages:${IMAGE_TAG}
